export const theme = {
  colors: {
    primary: '#5B9BE7',
    primaryLight: '#7DD3FC',
    background: '#0E141B',
    backgroundSecondary: '#101A25',
    surface: '#121B28',
    surfaceElevated: '#182331',
    input: '#0B121A',
    text: '#EEF6FF',
    textSecondary: '#94A3B8',
    textMuted: '#64748B',
    border: '#243447',
    error: '#F87171',
    success: '#34D399',
    warning: '#FBBF24',
    white: '#FFFFFF',
    transparent: 'transparent',
    messageSent: '#5288C1',
    messageReceived: '#182331',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  typography: {
    h1: { fontSize: 32, fontWeight: 'bold' as const },
    h2: { fontSize: 24, fontWeight: 'bold' as const },
    h3: { fontSize: 18, fontWeight: '600' as const },
    body: { fontSize: 16, fontWeight: 'normal' as const },
    caption: { fontSize: 12, fontWeight: 'normal' as const },
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 16,
    xl: 24,
    full: 9999,
  },
};

export type Theme = typeof theme;
